import { createApi } from "./router.js";

const $ = (selector) => document.querySelector(selector);
const api = createApi();
const empty = () => $("#empty").content.cloneNode(true);
const formatTime = (time) => new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(time));
const text = (value) => document.createTextNode(String(value ?? ""));
function statusClass(status) { return `status ${String(status).replaceAll("_", "-")}`; }
function renderTopology(agent) { const host = $("#topology"); host.replaceChildren(); ["MCP host", "MeshLink adapter", agent?.name ?? "MeshLink Node", "Local policy", "Capability handler"].forEach((value) => { const item = document.createElement("div"); item.className = "route"; item.append(text(value)); host.append(item); }); }
function renderAgents(agents) { const host = $("#agents"); host.replaceChildren(); if (!agents.length) return host.append(empty()); agents.forEach((agent) => { const item = document.createElement("article"); item.className = "agent"; const title = document.createElement("b"); title.append(text(agent.name)); const endpoint = document.createElement("small"); endpoint.append(text(agent.endpoint)); item.append(title, endpoint); host.append(item); }); }
function renderTasks(tasks) { const host = $("#tasks"); host.replaceChildren(); if (!tasks.length) return host.append(empty()); tasks.slice(0, 6).forEach((task) => { const item = document.createElement("article"); item.className = "task"; item.append(text(`${task.request.targetCapability} — ${task.status} — ${task.result?.summary ?? task.error?.message ?? task.request.input.instruction ?? "Waiting for execution"}`)); host.append(item); }); }
function renderAudit(events) { const host = $("#audit"); host.replaceChildren(); if (!events.length) return host.append(empty()); events.slice().reverse().slice(0, 7).forEach((event) => { const item = document.createElement("li"); item.append(text(`${event.action} — ${event.caller} — ${event.capability} — ${formatTime(event.at)}`)); host.append(item); }); }
async function refresh() { const button = $("#refresh"); button.disabled = true; try { const [health, agentResponse, taskResponse, auditResponse] = await Promise.all([api("/health"), api("/dashboard/api/agents"), api("/dashboard/api/tasks"), api("/dashboard/api/audit")]); if (!health.ok) throw new Error("Node unavailable"); const [{ agents }, { tasks }, { events }] = await Promise.all([agentResponse.json(), taskResponse.json(), auditResponse.json()]); $("#connection").textContent = "Node online"; $("#connection-dot").classList.add("online"); $("#agent-count").textContent = agents.length; $("#task-count").textContent = tasks.length; $("#approval-count").textContent = tasks.filter((task) => task.status === "awaiting_approval").length; renderTopology(agents[0]); renderAgents(agents); renderTasks(tasks); renderAudit(events); } catch (error) { if (error?.message !== "DASHBOARD_AUTH_REQUIRED") { $("#connection").textContent = "Node offline"; $("#connection-dot").classList.remove("online"); } } finally { button.disabled = false; } }
$("#refresh").addEventListener("click", refresh); refresh();